#! /bin/bash

# Build the UI
cd src/ui
npm run deploy

# Check for changes
git diff-index --quiet HEAD
if [ $? -eq 1 ]; then
  # Stage all changes
  git add -A

  # Commit the changes
  git commit -n -q -m "chore: rebuild the project"
fi
