name: Server code CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/server/**'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: pylint

      - name: Upload Pylint results as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: pylint-results
          path: pylint.log
